trigger:
- main

pool:
  name:  'webgoat-agent'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactName: 'drop'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x' # Use the latest 8.0.x version available

- script: dotnet --version
  displayName: 'Check .NET SDK Version'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: |
    echo "Restoring .NET packages..."
    dotnet restore
  displayName: 'Restore .NET Packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build .NET Project'

- script: |
    echo "Publishing .NET project..."
    dotnet publish $(solution) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish .NET Project'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: '$(artifactName)'
    publishLocation: 'pipeline'

