trigger:
  branches:
    include:
      - main
  #paths:
   # include:
    #  - src/WebApp/*
     ##- src/ServiceDefaults/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
      - job: BuildFrontend
        displayName: 'Build Frontend'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Restore'
            inputs:
              command: restore
              projects: 'src/WebApp/WebApp.csproj'

          - task: DotNetCoreCLI@2
            displayName: 'Publish'
            inputs:
              command: publish
              projects: 'src/WebApp/WebApp.csproj'
              publishWebProjects: false
              arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
              zipAfterPublish: true

          - publish: '$(Build.ArtifactStagingDirectory)'
            artifact: webapp-drop # artifact name

  - stage: DeployToDev
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeployWebApp
        environment: 'eshop-dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: 'Deploy to App Service (dev)'
                  inputs:
                    azureSubscription: 'ado-to-azure-auth/authz'
                    appType: 'webApp'
                    appName: 'kaseyaeshop'
                    package: '$(Pipeline.Workspace)/webapp-drop/**/*.zip'
